Script started on 廿十七年三月十三日 (週一) 廿三時58分十七秒
]0;jameswang@jameswang-VirtualBox: ~/lab1[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~/lab1[00m$ ./lab1g++ lab1.cpp -o lab1ls[Kgit commit -m /add/[10Padd .commit -m /add/ls[Kg++ lab1.cpp -o lab1
]0;jameswang@jameswang-VirtualBox: ~/lab1[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~/lab1[00m$ g++ lab1.cpp -o lab1./lab1[Kg++ lab1.cpp -o lab1./lab1[K
22
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
]0;jameswang@jameswang-VirtualBox: ~/lab1[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~/lab1[00m$ exit

Script done on 廿十七年三月十三日 (週一) 廿三時58分40秒
