Script started on 廿十七年三月三日 (週五) 十四時廿六分36秒
]0;jameswang@jameswang-VirtualBox: ~[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~[00m$ whoami; pwd
jameswang
/home/jameswang
]0;jameswang@jameswang-VirtualBox: ~[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~[00m$ git config -l
]0;jameswang@jameswang-VirtualBox: ~[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~[00m$ git clone http://GITBUB.COM[K[K[K[K[K[K[K[K[K[Kgithub.com/jameswang0/lab1.gi t
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
]0;jameswang@jameswang-VirtualBox: ~[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~[00m$ exit

Script done on 廿十七年三月三日 (週五) 十四時廿九分卅一秒
