Script started on 廿十七年三月十四日 (週二) 〇時二分35秒
]0;jameswang@jameswang-VirtualBox: ~/lab1[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~/lab1[00m$ whoami;pwqd[K[Kd
jameswang
/home/jameswang/lab1
]0;jameswang@jameswang-VirtualBox: ~/lab1[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~/lab1[00m$ git config -l
user.email=jason980160@gmail.com
user.name=jameswang0
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=http://github.com/jameswang0/lab1.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
]0;jameswang@jameswang-VirtualBox: ~/lab1[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~/lab1[00m$ git clone https://github.com/jameswang0/l ab1.git
fatal: destination path 'lab1' already exists and is not an empty directory.
]0;jameswang@jameswang-VirtualBox: ~/lab1[01;32mjameswang@jameswang-VirtualBox[00m:[01;34m~/lab1[00m$ exit

Script done on 廿十七年三月十四日 (週二) 〇時三分廿九秒
